server:
  port: 8080

spring:
  application:
    name: hubspot
  security:
    oauth2:
      client:
        registration:
          hubspot:
            clientId: ${CLIENT_ID}
            clientSecret: ${CLIENT_SECRET}
            authorization-grant-type: authorization_code
            redirect-uri: ${REDIRECT_URI:http://localhost:8080/v1/oauth-callback}
            scope:
              - crm.objects.contacts.read
              - crm.objects.contacts.write
        provider:
          hubspot:
            authorization-uri: https://app.hubspot.com/oauth/authorize
            token-uri: https://api.hubapi.com/oauth/v1/token
