spring:
  application:
    name: hubspot
  security:
    oauth2:
      client:
        registration:
          hubspot:
            clientId: 123
            clientSecret: abc
            authorization-grant-type: authorization_code
            redirect-uri: http://localhost:8080/v1/oauth-callback
            scope:
              - crm.objects.contacts.read
              - crm.objects.contacts.write
        provider:
          hubspot:
            authorization-uri: https://app.hubspot.com/oauth/authorize
            token-uri: https://api.hubapi.com/oauth/v1/token
